### ISSUE TITLE
Missing Bytes After Encrypt and Decrypt Large files

### ISSUE THREAD

**Issue by jhkuan1989** [mattosaurus/PgpCore#70] opened 2020-06-01 05:05 UTC
Not too sure if anyone have experience this, I've tried to test if the PGP works on large files using the settings below.

            using (PGP pgp = new PGP()
            {
                CompressionAlgorithm = Org.BouncyCastle.Bcpg.CompressionAlgorithmTag.Uncompressed,
                SymmetricKeyAlgorithm = Org.BouncyCastle.Bcpg.SymmetricKeyAlgorithmTag.Aes256,
                PublicKeyAlgorithm = Org.BouncyCastle.Bcpg.PublicKeyAlgorithmTag.RsaSign,
                HashAlgorithmTag = Org.BouncyCastle.Bcpg.HashAlgorithmTag.Sha512,
                FileType = PGPFileType.Binary,
                PgpSignatureType = PgpSignature.BinaryDocument
            })

So far for smaller files (<1GB) I'm getting exactly same size after the encrypt and decrypt process. but for 1 of my sql server db backup that is sized at 6GB, there's a 53KB mismatched, and resulting in a corrupted file.

![image](https://user-images.githubusercontent.com/16537515/83377485-312dcc00-a408-11ea-8ede-36d0ea320a53.png)

**Comment by mattosaurus** [comment] 2020-06-01 09:48
Strange, I haven't experienced that before. I don't suppose you're able to open the file and see if there's anything obviously wrong with it (missing characters from the end maybe)?

I don't have any 6GB SQL backups available but I'll see if I can replicate this with a txt file.

**Comment by jhkuan1989** [comment] 2020-06-02 04:17
yeap, did a quick check using large text file editor. Indeed it was truncated from the end. 

left being the original, right being the decrypted
![image](https://user-images.githubusercontent.com/16537515/83479179-6c90cf00-a4ca-11ea-96c6-f48b0622f0ac.png)

I've also tried simply zipping a random folder in my harddisk with size 5gb+, also having missing bytes.

**Comment by mattosaurus** [comment] 2020-06-02 06:50
Ok, thanks for checking. It sounds like it's probably closing the stream before it's flushed so is leaving off the end so I'll have a look into that.

Can you confirm that the issue is with the latest v2.4.0 version of the library?

**Comment by mattosaurus** [comment] 2020-06-29 16:16
This was an issue with the encryption method not writing all bytes for large files. I've fixed it now and have published v2.4.1.

**Closed by mattosaurus** 2020-06-29 16:16 UTC
