### ISSUE TITLE
"Cannot Access a closed stream" error with PGPCore 5.4.0 and Portable.BouncyCastle 1.9.0

### ISSUE THREAD

**Issue by robert-shattock** [mattosaurus/PgpCore#140] opened 2021-11-17 22:39 UTC
As flagged in https://github.com/mattosaurus/PgpCore/issues/139 (closed because there is a workaround, not because it was resolved), code such as the following will get a "Cannot Access a closed stream" error with PGPCore 5.4.0 and Portable.BouncyCastle 1.9.0.  The issue has been around a while as I was getting the same error with PGPCore 3,2,0 and Portable.BouncyCastle 1.9.0 (current workaround is to use Portable.BouncyCastle 1.8.10).
```
using (PGP pgp = new PGP())
{
   pgp.DecryptFile(encryptedFilesFromLocalFolder[i], decryptedFileLocalPath, privateKeyForDecryptingFilesLocalPath, Config.GetSetting("PassPhraseForDecryptingFiles"));
}
```
So for me it's not urgent as I have a usable workaround but obviously it's going to potentially cause issues for others who don't realise.

(p.s. Thanks for your effort in building a great library!)

**Comment by mattosaurus** [comment] 2021-11-19 09:57
Thanks for looking into this, I'll leave this issue open and hopefully this is something the BouncyCastle team will fix soon.

**Comment by jsil3601** [comment] 2022-03-12 23:36
Currently this issue still exist in with pgp core 5.5
Is there an open issue for this with bouncycastle? Anyone know if it's planned to be fixed?

**Comment by mattosaurus** [comment] 2022-03-14 09:43
Hi, I thought an issue for this had been raised but I can't see it in the bouncy castle repo. I'm not really sure what's causing it or how to reproduce it so if you're able to identify the specific issue I'd be grateful if you could raise an issue for it.

All the project tests run sucessfully for me which is why I haven't done anything about it. The suggested workaround from #139 is to not use v1.9.0 of bouncy castle in your project if you're adding in extra functionality that's not provided by PgpCore.

**Comment by robert-shattock** [comment] 2022-03-14 22:34
Hi @mattosaurus , doesn't this show you how to reproduce the issue https://github.com/mattosaurus/PgpCore/issues/140#issue-1056703324?  As you can see it's only calling a PgpCore method (which behind the scenes must be using Bouncy Castle).

**Comment by mattosaurus** [comment] 2022-03-18 09:58
Sorry, that does indeed provide an example of the issue.

I was about to try and debug it and see if I could figure out exactly what the issue with the Bouncy Castle libray is so I could raise an issue with them, but interestingly it looks like they've delisted versions 1.8.10 and 1.9.0 from NuGet. Maybe this was part of a wider problem with the library.

As this works with the now current v1.8.9 version of Bouncy Castle I don't think this is an issue anymore (until the next version maybe).

**Comment by RodneyRichardson** [comment] 2022-06-24 15:43
v1.9.0 looks to be available on NuGet: https://www.nuget.org/packages/Portable.BouncyCastle/#versions-body-tab

**Comment by gtbuchanan** [comment] 2022-08-31 20:54
We just ran into this issue when we referenced MailKit/MimeKit because it has `Portable.BouncyCastle >= 1.9.0` listed as a dependency. Has anybody made any new discoveries here?

**Comment by mattosaurus** [comment] 2022-09-02 09:02
So I can't seem to replicate this

I've updated the bouncy castle version to v1.9 and all the tests pass which I seem to remember wasn't the case previously.

Are you able to test this PR and let me know if it solves the issue.

https://github.com/mattosaurus/PgpCore/pull/172

Or alternativly provide me with a demo project demonstrating the error that I can look into a bit more.

**Comment by gtbuchanan** [comment] 2022-09-02 13:25
@mattosaurus It seems we're unable to reproduce this outside of our production environment. I suspect it is related to a difference in keys or the way the file was encrypted. I am working on trying to reproduce it in a separate project and will let you know if/when I'm able to.

**Comment by mattosaurus** [comment] 2022-09-02 13:32
If you can't reproduce it can you build PgpCore from the PR branch linked above and use that on your prod enviroment instead of the package from NuGet?

I've updated Bouncy Castle to 1.9 in it so that might fix it if it's a version clash.

**Comment by gtbuchanan** [comment] 2022-09-02 14:06
@mattosaurus I was able to reproduce it in my local environment using our production key and customer file using a build from the PR. I obviously won't be able to provide those so I am trying to figure out what settings in this particular key or encrypted file might be causing the issue.

**Comment by mattosaurus** [comment] 2022-09-02 14:13
Ok, so upgrading the Bouncy Castle version doesn't fix it then.

There's another PR where the streams aren't disposed which may fix the issue.

https://github.com/mattosaurus/PgpCore/pull/155

This removes the using statements from the streams which I didn't like as a solution (hence why it's not merged) but you could try that in your local build of PgpCore and see if it works.

**Comment by gtbuchanan** [comment] 2022-09-02 14:39
I re-encrypted the file and the new file does not cause the error so it seems to be related in some way to how our customer encrypted the original file.

> This removes the using statements from the streams which I didn't like as a solution (hence why it's not merged) but you could try that in your local build of PgpCore and see if it works.

PR 155 does seem to resolve the issue when we switch from `DecryptStreamAsync` to `DecryptStream`. `DecryptAsync` doesn't appear to have been updated to remove the using statements.

**Closed** 2022-09-02 22:07 UTC
